variable "environment" {}
variable "project" {}
variable "region" {}
variable "vpc_cidr" {}
variable "availability_zones" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "allowed_ports" {}
variable "public_instance_type" {}
variable "private_instance_type" {}
variable "ami_id" {}
variable "key_name" {}
variable "instance_count" {}